Blog App: Views
Mike111222/BlogApp pull request #6
Opened 2023-09-27 12:39 UTC by Mike111222

- Implement the design from the sneak peek wireframes.
- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- homepage
- user
- posts
- post
- Comments

2023-09-27 13:57 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi :wave:  @Mike111222 , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done working on the views. ✔


## Required Changes ♻️

- [ ] Well done adding the seeds. :clap: 
### seed file :point_down: 
![Screenshot from 2023-09-27 13-25-50](https://github.com/Mike111222/BlogApp/assets/89228743/665de24b-53ba-42dd-bc72-100067e3c941)



However, when running the `rails db:seed` command I got the  below error. 
### Error :point_down: 
![Screenshot from 2023-09-27 13-07-25](https://github.com/Mike111222/BlogApp/assets/89228743/21d53f8b-f998-49ed-a72f-bbe1740d5b51)
I know it's not required to add data into the `seed` file. I tried creating a user using the console and it was successful. However, I am unable to create a post despite trying 🤔. I have not yet attempted to create a comment as I need to create a post first. Could you please look into this issue and fix it so that we can create posts and comments without any problems? 🙏 

### attempt to create a post on the console :point_down: 
![Screenshot from 2023-09-27 13-52-49](https://github.com/Mike111222/BlogApp/assets/89228743/8daf925f-0d28-416e-824b-ff30e73990ae)








## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 18:29 UTC, Mike111222 commented
I have made all the changes you suggested. Now I have no errors in the console. Thanks a lo for your kind feedback.

2023-09-28 19:06 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @Mike111222, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- App design aligns with given design :+1:  

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 19:06 UTC, FrederickMih commented on app/views/users/index.html.erb
> +            </div>
- [Optional] I think it would be nice if we endeavor to promote the DRY principle by enabling the reuse of code across codebase. This is made possible in Rails by partials. This piece of code has been reused across our codebase.

2023-09-28 19:06 UTC, FrederickMih commented on app/views/users/index.html.erb
> +            <div class="user-image border"></div>
- [Optional] I think user image was supposed to be retrieved from the db and display here instead of styling this div :+1:

2023-09-29 04:12 UTC, merged